### ISSUE TITLE
Undefined behavior in testsuite

### ISSUE THREAD

**Issue by cgzones** [mvanderkolff/jbigkit-packaging#7]
Running the testsuite reveals some undefined behavior:

```
# apply Debian patches ...
make clean
make CC=clang-15 CFLAGS='-O1 -g -ftrivial-auto-var-init=pattern -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-address-use-after-return=always -fno-omit-frame-pointer -fsanitize=undefined -fsanitize=nullability -fsanitize=float-divide-by-zero -fsanitize=local-bounds -fPIC' LDFLAGS='-ftrivial-auto-var-init=pattern -fsanitize=address -fsanitize-address-use-after-scope -fsanitize-address-use-after-return=always -fno-omit-frame-pointer -fsanitize=undefined -fsanitize=nullability -fsanitize=float-divide-by-zero -fsanitize=local-bounds'
UBSAN_OPTIONS=print_stacktrace=1:print_summary=1:halt_on_error=0 make test
```

```
3) Parametric algorithm test sequence from ITU-T T.82, clause 7.2
-----------------------------------------------------------------

Generating test image ...

Test-85 3.1: TPBON=0, Mx=0, LRLTWO=0, L0=1951, 0 layers

Test-85 3.1.1: Encoding ...
tstcodec85.c:168:15: runtime error: addition of unsigned offset to 0x7fc81e613800 overflowed to 0x7fc81e61370b
    #0 0x564b6898b1b3 in test_cycle /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:168:15
    #1 0x564b68989db6 in main /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:413:15
    #2 0x7fc81ec29209 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #3 0x7fc81ec292bb in __libc_start_main csu/../csu/libc-start.c:389:3
    #4 0x564b688c9310 in _start (/home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85+0x33310) (BuildId: 7b5b1a9cf66f1ee5ea3278e17cabbc1d883c266c)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior tstcodec85.c:168:15 in 
tstcodec85.c:169:15: runtime error: addition of unsigned offset to 0x7fc81e613800 overflowed to 0x7fc81e613616
    #0 0x564b6898b1cc in test_cycle /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:169:15
    #1 0x564b68989db6 in main /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:413:15
    #2 0x7fc81ec29209 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #3 0x7fc81ec292bb in __libc_start_main csu/../csu/libc-start.c:389:3
    #4 0x564b688c9310 in _start (/home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85+0x33310) (BuildId: 7b5b1a9cf66f1ee5ea3278e17cabbc1d883c266c)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior tstcodec85.c:169:15 in 
Encoded BIE has 317384 bytes: PASSED
Test-85 3.1.2: Decoding whole chunk ...
jbig85.c:630:23: runtime error: addition of unsigned offset to 0x617000000080 overflowed to 0x616fffffff8b
    #0 0x564b6899fd43 in decode_pscd /home/christian/Downloads/jbigkit/jbigkit/libjbig/jbig85.c:630:23
    #1 0x564b689973d8 in jbg85_dec_in /home/christian/Downloads/jbigkit/jbigkit/libjbig/jbig85.c:1055:15
    #2 0x564b6898b2a6 in test_cycle /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:188:12
    #3 0x564b68989db6 in main /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:413:15
    #4 0x7fc81ec29209 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #5 0x7fc81ec292bb in __libc_start_main csu/../csu/libc-start.c:389:3
    #6 0x564b688c9310 in _start (/home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85+0x33310) (BuildId: 7b5b1a9cf66f1ee5ea3278e17cabbc1d883c266c)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior jbig85.c:630:23 in 
jbig85.c:631:23: runtime error: addition of unsigned offset to 0x617000000080 overflowed to 0x616fffffff8b
    #0 0x564b6899fe1c in decode_pscd /home/christian/Downloads/jbigkit/jbigkit/libjbig/jbig85.c:631:23
    #1 0x564b689973d8 in jbg85_dec_in /home/christian/Downloads/jbigkit/jbigkit/libjbig/jbig85.c:1055:15
    #2 0x564b6898b2a6 in test_cycle /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:188:12
    #3 0x564b68989db6 in main /home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85.c:413:15
    #4 0x7fc81ec29209 in __libc_start_call_main csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    #5 0x7fc81ec292bb in __libc_start_main csu/../csu/libc-start.c:389:3
    #6 0x564b688c9310 in _start (/home/christian/Downloads/jbigkit/jbigkit/libjbig/tstcodec85+0x33310) (BuildId: 7b5b1a9cf66f1ee5ea3278e17cabbc1d883c266c)
```

**Comment by mvanderkolff** [comment]
This strikes me as an upstream issue - forward to Markus.Kuhn@cl.cam.ac.uk?
